services:
  # ---- Frontend (Static Site) ----
  - type: web
    runtime: static
    name: XAI-frontend
    buildCommand: cd web && npm ci && npm run build
    staticPublishPath: web/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # ---- Backend (Flask Web Service) ----
  - type: web
    runtime: python
    name: XAI-api
    plan: free
    buildCommand: pip install -r api/requirements.txt
    startCommand: cd api && gunicorn server:app -b 0.0.0.0:$PORT -w 2
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: FRONTEND_ORIGIN
        value: "*"
    buildFilter:
      paths:
        - api/**
